name: textatize_landing
description: Textatize Media Landing
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.3 # State Managment Solution
  bloc: ^8.1.2 # BLoC Dependency
  meta: ^1.9.1 # BLoC Dependency

  # Web Helpers
  http: ^0.13.6 # To make API calls
  cached_network_image: ^3.2.3 # Saving Memory

  # Other
  cupertino_icons: ^1.0.2 # Default Flutter Dependency
  universal_html: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
